import java.util.Scanner;

public class Menu {
    public static void main(String[] args) {
            Scanner scanner = new Scanner(System.in);
                    int opcion;

                            do {
                                        System.out.println("Menú");
                                                    System.out.println("1. Opción 1");
                                                                System.out.println("2. Opción 2");
                                                                            System.out.println("3. Opción 3");
                                                                                        System.out.println("4. Opción 4");
                                                                                                    System.out.println("5. Opción 5");
                                                                                                                System.out.println("6. Opción 6");
                                                                                                                            System.out.println("7. Salir");

                                                                                                                                        System.out.print("Ingrese su opción: ");
                                                                                                                                                    opcion = scanner.nextInt();

                                                                                                                                                                switch (opcion) {
                                                                                                                                                                                case 1:
                                                                                                                                                                                                    System.out.println("Has seleccionado la opción 1");
                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                        case 2:
                                                                                                                                                                                                                                                            System.out.println("Has seleccionado la opción 2");
                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                case 3:
                                                                                                                                                                                                                                                                                                                    System.out.println("Has seleccionado la opción 3");
                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                        case 4:
                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Has seleccionado la opción 4");
                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                case 5:
                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Has seleccionado la opción 5");
                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 6:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Has seleccionado la opción 6");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 7:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Adiós");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Opción inválida");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } while (opcion != 7);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ```

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cómo